on:
  push:
    paths:
      - 'config/**'
  workflow_dispatch:

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:2.5
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export

      - name: West Build (KBD533-LPHS Left)
        run: west build -p -s zmk/app -b kbd533-lphs_left -d kbd533-lphs_left -- -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: KBD533-LPHS DTS File
        if: ${{ always() }}
        run: cat -n kbd533-lphs_left/zephyr/kbd533-lphs_left.dts.pre.tmp
      - name: KBD533-LPHS Left Kconfig file
        run: cat kbd533-lphs_left/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp kbd533-lphs_left/zephyr/zmk.uf2 kbd533-lphs_left.uf2
      - name: Archive (KBD533-LPHS Left)
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: kbd533-lphs_left.uf2

      - name: West Build (KBD533-LPHS Right)
        run: west build -p -s zmk/app -b kbd533-lphs_right -d kbd533-lphs_right -- -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: KBD533-LPHS DTS File
        if: ${{ always() }}
        run: cat -n kbd533-lphs_right/zephyr/kbd533-lphs_right.dts.pre.tmp
      - name: KBD533-LPHS Right Kconfig file
        run: cat kbd533-lphs_right/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp kbd533-lphs_right/zephyr/zmk.uf2 kbd533-lphs_right.uf2
      - name: Archive (KBD533-LPHS Right)
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: kbd533-lphs_right.uf2
